server:
  port: 8081
spring:
  application:
    name: mq-service-consumer
  cloud:
    function:
      definition: sink;input;
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      default-binder: kafka
      bindings:
        sink-in-0:
          destination: message-center
          contentType: application/json
          group: ${spring.application.name}
          binder: rabbit
        input-in-0:
          destination: kafka-center
          contentType: application/json
          binder: kafka
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest