server:
  port: 8080
spring:
  application:
    name: mq-service-producer
  cloud:
    function:
      definition: source;output;
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      default-binder: kafka
      bindings:
        source-out-0:
          destination: message-center
          contentType: application/json
          group: ${spring.application.name}
          binder: rabbit
        output-out-0:
          destination: kafka-center
          contentType: application/json
          binder: kafka
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest